package enums;

public enum STATEMENT {
    STATEMENT_INSERT,
    STATEMENT_SELECT,
    STATEMENT_SELECT_ROLE,
    STATEMENT_UPDATE,
    STATEMENT_DELETE,
    STATEMENT_PRINT,
    STATEMENT_SAVE,
    STATEMENT_NULL
}
